### ISSUE TITLE
Code include code coverage

### ISSUE THREAD

**Issue by napulen** [DDMAL/MEI2Volpiano#42]
It'd be relatively easy to include code coverage of the tests in this repository.

I have been trying the `coverage` Python package with the [codecov](https://about.codecov.io/) service, integrated via github-actions. It's very simple to set up. Something like this on the gh-actions workflow suffices:

```yaml
    - name: Test with pytest and coverage
      run: |
        coverage run -m pytest
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
        fail_ci_if_error: true
        verbose: true
```

`coverage` needs to be included in the requirements/dependencies
